# Adam's Starship Config
#
# Docs: https://starship.rs/config
# font: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
# icon reference: https://www.nerdfonts.com/cheat-sheet (use copy icon)

# Don't print a new line at the start of the prompt
add_newline = false

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
vicmd_symbol = "[ ](bold green)"
# success_symbol = "[](bold green)"
# error_symbol = "[](bold red)"
# vicmd_symbol = "[](bold green)"

[cmd_duration]
show_notifications = false
format = "[ 鬒$duration]($style)"

[username]
format = "[𣏕$user]($style) "
disabled = false
show_always = true

# [hostname]
# ssh_only = false
# format = "[異$hostname]($style) "
# style = "bold red"

[directory]
read_only = "  "
format = "[ $path]($style)[$read_only]($read_only_style)"
style = "bold cyan"
truncation_length = 1
home_symbol = "\\e[2D  " # go back 2 characters and overwrite the folder symbol

[git_branch]
# symbol = " "
symbol = " "
format = " [$symbol$branch]($style)"
style = "bold bright-green"
truncation_length = 30

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "bold yellow"

[elixir]
symbol = " "
format = ' [$symbol($version )]($style)[ ($otp_version)](bold red)'

[erlang]
symbol = " "
format = ' [$symbol($version )]($style)'

[rust]
symbol = " "
format = " [$symbol($version )]($style)"

[nodejs]
symbol = " "
format = " [$symbol($version )]($style)"
disabled = false

[ruby]
symbol = " "
format = " [$symbol($version )]($style)"
# 
# 

[package]
symbol = " "
disabled = true

[aws]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[swift]
symbol = "ﯣ "
