# Don't print a new line at the start of the prompt
add_newline = false
command_timeout = 100

[character]
success_symbol = "[îŠ…](bold green)"
error_symbol = "[îŠ…](bold red)"
vicmd_symbol = "[îŸ… îŠ…](bold green)"
# success_symbol = "[ïƒš](bold green)"
# error_symbol = "[ïƒš](bold red)"
# vicmd_symbol = "[ïƒ™](bold green)"

[cmd_duration]
show_notifications = false
format = "[ ï«$duration]($style)"

[username]
format = "[ğŸ¥ƒ $user]($style) "
disabled = false
show_always = true

# [hostname]
# ssh_only = false
# format = "[ï¥¢$hostname]($style) "
# style = "bold red"

[directory]
read_only = " ï ½ "
format = "[ï» $path]($style) [$read_only]($read_only_style)"
style = "bold cyan"
truncation_length = 1
home_symbol = "ï€•" # go back 2 characters and overwrite the folder symbol

[git_branch]
# symbol = "ï˜ "
symbol = "ï‡’ "
format = " [$symbol$branch]($style) "
style = "bold bright-green"
truncation_length = 30

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "bold yellow"

[elixir]
symbol = "î˜­ "
# format = '[$symbol($version )]($style)[î± ($otp_version)](bold red)'
format = 'via [$symbol($version \(OTP $otp_version\) )]($style)'

[erlang]
symbol = "î± "
format = ' [$symbol($version )]($style)'

[rust]
symbol = "î¨ "
format = " [$symbol($version )]($style)"

[nodejs]
symbol = "î‰ "
format = " [$symbol($version )]($style)"
disabled = false

[ruby]
symbol = "î‘ "
format = " [$symbol($version )]($style)"
# îœ¹
# î‘

[package]
symbol = "ï£– "
disabled = true

[aws]
symbol = "îŒ½ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

# [docker]
# symbol = "ïŒˆ "

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"

[elm]
symbol = "î˜¬ "

[golang]
symbol = "î˜§ "

# [haskell]
# symbol = "î˜Ÿ "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[perl]
symbol = "î© "

[php]
symbol = "î˜ˆ "

[python]
symbol = "î˜† "

[swift]
symbol = "ï¯£ "
